name: 'Run TestingHelper'
author: 'rulasg'
description: 'Run tests for a PowerShell Module using TestingHelper'
branding:
  icon: "check-circle"
  color: "orange"
inputs:
  Version:
    description: 'Specifies which version of TestingHelper to use.'
    required: false
  AllowPreReleaseVersions:
    description: 'Allow the use of prerelease version of TestingHelper'
    default: 'true'
    required: false
#     AllowedSkippedTests:
#       description: 'Allow to use PreRelease versions onf TestingHelper module'
#       required: false
#     AllowedSkippedTests:
#       description: 'Allow tests to be skipped without failing'
#       required: false
#     AllowedNotImplementedTests:
#       description: 'Allow tests to be skipped without failing'
#       required: false
runs:
  using: "composite"
  steps:
    - name: Run TestingHelper
      shell: pwsh
      run: |

        # Import TestingHelper
        Import-Module TestingHelper -Force

        # Execute tests and safe result
        $result = Invoke-TestingHelper -Path '.' -ShowTestErrors

        # Display results
        $result

        # Allow Not Implemented and Skipped tests to pass
        $passed = $result.Tests -eq $result.Pass + $result.NotImplemented + $result.Skipped
        # $passed = $result.Tests -eq $result.Pass

        if($passed)
        { "All test passed" | Write-Verbose -verbose ; exit 0 } 
        else 
        { "Not all tests passed" | Write-Verbose -verbose ; exit 1 }